main: eu.union.dev.PvPMain
version: 1.1-SNAPSHOT
name: UnionPvP

commands:
  kit:
  kits:
  gm:
  build:
  setspawn:
  spawn:
  stats:
  recon:
  reset:
  check:
  ready:
  level:
  inv:
  fake:
  cc:
  admin:
  setfps:
  report:
  fps:
  setlavachallenge:
    aliases: [setlc]
  lavachallenge:
    aliases: [lc]
  setclick:
  click:
  warps:
    aliases: [warp]